training_recipes = [
    ("blueberry-pecan streusel pie", "dessert"),
    ('mixed berry and white chocolate mousse pie', 'dessert'),
    ('turtle bundt cake', 'dessert'),
    ('double layer pumpkin cheesecake', 'dessert'),
    ('best chocolate chip cookies', 'dessert'),
    ('classic birthday cake', 'dessert'),
    ('double fudge chocolate brownies', 'dessert'),
    ('peach and blackberry cobbler', 'dessert'),
    ('grandma\'s apple pie', 'dessert'),
    ('classic creme brulee', 'dessert'),
    ('homemade easy ice cream', 'dessert'),
    ('peanut butter cookie', 'dessert'),
    ('old fashioned donuts', 'dessert'),
    ('the perfect skirt steak', 'meat'),
    ('texas bbq brisket', 'meat'),
    ('pork dumplings', 'meat'),
    ('crispy slow-roasted pork shoulder', 'meat'),
    ('glazed pork tenderloin', 'meat'),
    ('souther fried chicken', 'meat'),
    ('meat loaf', 'meat'),
    ('swedish meatballs', 'meat'),
    ('bistro style beef burger', 'meat'),
    ('apple glazed ribs', 'meat'),
    ('spicy coconut chicken curry', 'meat'),
    ('lamb kebab with bean stew', 'meat'),
    ('one skillet italian sausage pasta', 'meat'),
    ('sirloin steak with garlic butter', 'meat'),
    ('beet salad with goat cheese', 'vegetable'),
    ('sweet and sour brussel sprouts', 'vegetable'),
    ('provincial tomatoes', 'vegetable'),
    ('baked asparagus with balsamic sauce', 'vegetable'),
    ('green bean and mushroom medley', 'vegetable'),
    ('garlic mashed potatoes', 'vegetable'),
    ('orange glazed carrots', 'vegetable'),
    ('corn and zucchini melody', 'vegetable'),
    ('sweet potato fries', 'vegetable'),
    ('savory lentil sautee', 'vegetable'),
    ('acorn squash with apple', 'vegetable'),
    ('loaded baked potatoes', 'vegetable'),
    ('southern collard greens', 'vegetable'),
    ('chinese tofu medley', 'vegetable'),
    ('whipped butter potatoes', 'vegetable'),
    ('grilled fish tacos', 'seafood'),
    ('fresh salmon cakes with mayo', 'seafood'),
    ('shrimp quesadilla', 'seafood'),
    ('baked fish and chips', 'seafood'),
    ('old bay clam chowder', 'seafood'),
    ('pan seared scallops', 'seafood'),
    ('maine lobster roll', 'seafood'),
    ('butter tilapia', 'seafood'),
    ('lemon pepper scampi' , 'seafood'),
    ('curry shrimp with rice', 'seafood'),
    ('herb baked salmon', 'seafood'),
    ('steamd mussels and herb sauce', 'seafood')
 ]
